### PR TITLE
fix: create dir if not exists when configuring profile

### PR DESCRIPTION
**Pull request by sobolk**
## Problem

Fixes https://github.com/aws-amplify/amplify-backend/issues/881 .

**Issue number, if available:**

## Changes

Add logic to create directory if it doesn't exist yet when creating profile.

**Corresponding docs PR, if applicable:**

## Validation

Added unit test.

## Checklist

- [ ] If this PR includes a functional change to the runtime behavior of the code, I have added or updated automated test coverage for this change.
- [ ] If this PR requires a change to the [Project Architecture README](../PROJECT_ARCHITECTURE.md), I have included that update in this PR.
- [ ] If this PR requires a docs update, I have linked to that docs PR above.
- [ ] If this PR modifies E2E tests, makes changes to resource provisioning, or makes SDK calls, I have run the PR checks with the `run-e2e` label set.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by edwardfoyle — APPROVED** [review]

**Review by srquinn21 — COMMENTED** [review]
Changes look fine, but I'm not clear on how this code path is reached. `appendAWSFiles` is only to be called when appending to an existing profile which assumes the `.aws` folder would exist.

**Comment by sobolk** [comment]
> Changes look fine, but I'm not clear on how this code path is reached. `appendAWSFiles` is only to be called when appending to an existing profile which assumes the `.aws` folder would exist.

@srquinn21 see https://github.com/aws-amplify/amplify-backend/issues/881

**Comment by srquinn21** [comment]
> > Changes look fine, but I'm not clear on how this code path is reached. `appendAWSFiles` is only to be called when appending to an existing profile which assumes the `.aws` folder would exist.
> 
> @srquinn21 see #881

Thanks, saw that. But that seems like it should have take the Create path, not the Append path. Append path should only be taken if the files/directories already exist.

**Review by srquinn21 — APPROVED** [review]
Shipping with follow up to reconsider naming as `appendAWSFiles` is really `createOrAppendAWSFiles`

**Pull request merged**
