### PR TITLE
chore: bump data-schema packages version (0.16.0)

### PR DESCRIPTION
**Pull request by HuiSF**
## Problem

To integrate the latest changes made into `@aws-amplify/data-schema` and `@aws-amplify/data-schema-types` packages.

* https://github.com/aws-amplify/amplify-api-next/pull/178
* https://github.com/aws-amplify/amplify-api-next/pull/180
* https://github.com/aws-amplify/amplify-api-next/pull/167

**Issue number, if available:**

## Changes

* Bump @aws-amplify/data-schema version to 0.16.0
* Bump @aws-amplify/data-schema-types version to 0.9.0

**Corresponding docs PR, if applicable:**

https://github.com/aws-amplify/docs/pull/7251

## Checklist

- [ ] If this PR includes a functional change to the runtime behavior of the code, I have added or updated automated test coverage for this change.
- [ ] If this PR requires a change to the [Project Architecture README](../PROJECT_ARCHITECTURE.md), I have included that update in this PR.
- [x] If this PR requires a docs update, I have linked to that docs PR above.
- [ ] If this PR modifies E2E tests, makes changes to resource provisioning, or makes SDK calls, I have run the PR checks with the `run-e2e` label set.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Review by svidgen — DISMISSED** [review]

**Review by svidgen — APPROVED** [review]

**Review by sobolk — CHANGES_REQUESTED** [review]
please fix e2e tests.

**Comment by HuiSF** [comment]
> please fix e2e tests.

I double-checked that the integration testing suite used code has been refactored to fit the newly updated Data Auth rule builder interface.

The failures in the E2E check should be caused by the fact that the tests are pulling `aws-amplify@6.0.28`, which requires a lower version of data-schema packages, so the test projects resolve to the lower versions. Hence, the refactor code was not working with the outdated interface. I will mark this PR as draft for now, until `aws-amplify@6.0.29` gets released.

Thanks!

**Comment by sobolk** [comment]
> > please fix e2e tests.
> 
> I double-checked that the integration testing suite used code has been refactored to fit the newly updated Data Auth rule builder interface.
> 
> The failures in the E2E check probably were caused by the fact that the `@aws-amplify/backend` packages installed into the test projects is still pointing to `@aws-amplify/data-schema` while this PR bumps its version to `0.16.0`.

I looked at test logs and I can see two problems:
1. This test (https://github.com/aws-amplify/amplify-backend/actions/runs/8748311169/job/24008200339?pr=1339) failed on acquiring credentials, to mitigate this please push changes to branch in `amplify-backend` repo instead of fork and open new PR, this is known limitation to not allow acquiring creds if PR is from fork. I should have caught this earlier, sorry about that.
2. This test (https://github.com/aws-amplify/amplify-backend/actions/runs/8748311169/job/24008200211?pr=1339) however does print some errors and should be investigated. See screenshot below.

image

**Comment by HuiSF** [comment]
This PR is created from a branch in the forked repo, which limits the E2E testing. Closing the recreate.

**Pull request closed without merging**
